package Projeto;

import Classes.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class Acesso extends javax.swing.JFrame {

    dbConexao conexao = new dbConexao();

    public Acesso(String user) {

        initComponents();
        lblUser.setText(user);
        JOptionPane.showMessageDialog(null, "Seja bem vindo " + user + " !");
        setLocationRelativeTo(null);
        setIcon();
        if (Variable.nivel > 1) {
            jmCadastroColaborador.setEnabled(false);
            btnAlterarColaborador.setEnabled(false);
            jmAlterar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmCliente = new javax.swing.JMenu();
        jmListarCliente = new javax.swing.JMenuItem();
        jmInserir = new javax.swing.JMenu();
        jmProjeto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmCriar = new javax.swing.JMenuItem();
        jmAlterar = new javax.swing.JMenu();
        jmAlterarCadastro = new javax.swing.JMenu();
        jmFisico = new javax.swing.JMenuItem();
        jmCadastroJuridico = new javax.swing.JMenuItem();
        jmColaborador = new javax.swing.JMenu();
        jmCadastroColaborador = new javax.swing.JMenuItem();
        btnAlterarColaborador = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 430));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Software");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 170, 220, 60);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Construction");
        jLabel3.setMaximumSize(new java.awt.Dimension(155, 35));
        jLabel3.setMinimumSize(new java.awt.Dimension(155, 35));
        jLabel3.setPreferredSize(new java.awt.Dimension(155, 35));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 220, 150, 30);

        lblUser.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("usuario");
        lblUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblUser);
        lblUser.setBounds(10, 320, 150, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Background 2.0.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 710, 400);

        jmCliente.setText("Cliente   ");
        jmCliente.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jmListarCliente.setText("Listar Cliente");
        jmListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarClienteActionPerformed(evt);
            }
        });
        jmCliente.add(jmListarCliente);

        jmInserir.setText("Inserir");
        jmInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInserirActionPerformed(evt);
            }
        });

        jmProjeto.setText("Projeto");
        jmProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProjetoActionPerformed(evt);
            }
        });
        jmInserir.add(jmProjeto);

        jmCliente.add(jmInserir);

        jMenu3.setText("Cadastro");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmCriar.setText("Criar");
        jmCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCriarActionPerformed(evt);
            }
        });
        jMenu3.add(jmCriar);

        jmAlterar.setText("Alterar");

        jmAlterarCadastro.setText("Cadastro");

        jmFisico.setText("Fisico");
        jmFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFisicoActionPerformed(evt);
            }
        });
        jmAlterarCadastro.add(jmFisico);

        jmCadastroJuridico.setText("juridico");
        jmAlterarCadastro.add(jmCadastroJuridico);

        jmAlterar.add(jmAlterarCadastro);

        jMenu3.add(jmAlterar);

        jmCliente.add(jMenu3);

        jMenuBar2.add(jmCliente);

        jmColaborador.setText("Colaborador   ");
        jmColaborador.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jmCadastroColaborador.setText("Criar Cadastro");
        jmCadastroColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroColaboradorActionPerformed(evt);
            }
        });
        jmColaborador.add(jmCadastroColaborador);

        btnAlterarColaborador.setText("Alterar Cadastro");
        btnAlterarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarColaboradorActionPerformed(evt);
            }
        });
        jmColaborador.add(btnAlterarColaborador);

        jMenuBar2.add(jmColaborador);

        jmSair.setText("Sair");
        jmSair.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmSairKeyPressed(evt);
            }
        });
        jMenuBar2.add(jmSair);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCriarActionPerformed
        CadCliente proximo = new CadCliente();
        proximo.setVisible(true);


    }//GEN-LAST:event_jmCriarActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jmFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmFisicoActionPerformed

    private void jmCadastroColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroColaboradorActionPerformed
        Variable.habilitar = true;
        new CadColaborador().setVisible(true);

    }//GEN-LAST:event_jmCadastroColaboradorActionPerformed

    private void jmSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmSairKeyPressed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmSairKeyPressed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmSairActionPerformed

    private void btnAlterarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarColaboradorActionPerformed
        Variable.habilitar = false;
        new CadColaborador().setVisible(true);

    }//GEN-LAST:event_btnAlterarColaboradorActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarClienteActionPerformed
       new ListaCliente().setVisible(true);
    }//GEN-LAST:event_jmListarClienteActionPerformed

    private void jmInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInserirActionPerformed
        
        
    }//GEN-LAST:event_jmInserirActionPerformed

    private void jmProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProjetoActionPerformed
         new InserirProjeto().setVisible(true);
    }//GEN-LAST:event_jmProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Acesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAlterarColaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jmAlterar;
    private javax.swing.JMenu jmAlterarCadastro;
    private javax.swing.JMenuItem jmCadastroColaborador;
    private javax.swing.JMenuItem jmCadastroJuridico;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenu jmColaborador;
    private javax.swing.JMenuItem jmCriar;
    private javax.swing.JMenuItem jmFisico;
    private javax.swing.JMenu jmInserir;
    private javax.swing.JMenuItem jmListarCliente;
    private javax.swing.JMenuItem jmProjeto;
    private javax.swing.JMenu jmSair;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.acesso.jpg")));
    }

}
