/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto;

import Classes.*;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author italo
 */
public class CadColaborador extends javax.swing.JFrame {

    Funcionario funcionario = new Funcionario();
    dbConexao conexao = new dbConexao();

    public CadColaborador() {
        initComponents();
        setLocationRelativeTo(null);

        if (Variable.habilitar == false) {
            btnConsultar.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnCadastrar.setEnabled(false);
            tctCpf.grabFocus();
        } else {
            btnConsultar.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnCadastrar.setEnabled(true);
            txtNome.grabFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tctCpf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(520, 289));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 289));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));

        txtNome.setToolTipText("txtnome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 420, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Nìvel:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 50, 20));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Cpf:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 34, 14));

        tctCpf.setToolTipText("txtcpf");
        tctCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tctCpfActionPerformed(evt);
            }
        });
        tctCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tctCpfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tctCpfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tctCpfKeyTyped(evt);
            }
        });
        jPanel1.add(tctCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 170, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("Login:");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 20));

        txtLogin.setToolTipText("txtlogin");
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 240, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("Senha:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, -1));

        txtEmail.setToolTipText("txtemail");
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 420, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setText("Cargo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, -1));

        txtCargo.setToolTipText("txtcargo");
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCargoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 420, -1));

        btnConsultar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setToolTipText("btnconsultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        btnConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultarKeyPressed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        btnCadastrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("btncadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, -1));

        btnSair.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("btnalterar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, -1));

        lblId.setText("#######");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        btnAlterar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("btnalterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        btnAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAlterarKeyPressed(evt);
            }
        });
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 100, -1));

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 30, 20));

        txtNivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNivelKeyPressed(evt);
            }
        });
        jPanel1.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 110, 520, 240);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Software");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 220, 50);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Construction");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 80, 128, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Background 2.0.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 700));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 700));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if (txtNome.getText().length() >= 45) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Máximo 45 caractere.");
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void tctCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tctCpfKeyTyped
        if (tctCpf.getText().length() >= 11) {
            evt.consume();
            tctCpf.setText("");
            tctCpf.grabFocus();
            JOptionPane.showMessageDialog(null, "Máximo 11 dígitos.");
        }
    }//GEN-LAST:event_tctCpfKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            ArrayList<String> list = new ArrayList();

            Variable.cpf = tctCpf.getText();
            conexao.conectar();
            list = conexao.consultaFun();
            if (Variable.ckd) {
                lblId.setText(String.valueOf(list.get(0)));
                txtSenha.setText(list.get(1));
                txtLogin.setText(list.get(2));
                txtNome.setText(list.get(3));
                txtEmail.setText(list.get(4));
                txtCargo.setText(list.get(5));
                txtNivel.setText(list.get(6));
                Variable.cpf = "";
            } else {
                tctCpf.setText("");
                tctCpf.grabFocus();
                Variable.cpf = "";
            }
            Variable.ckd = false;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campos não pode ser vazio");
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tctCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tctCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tctCpfActionPerformed

    private void tctCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tctCpfKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctCpfKeyReleased

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String nome = txtNome.getText();
            funcionario.setNome(nome);
            String cpf = tctCpf.getText();
            funcionario.setCpf(cpf);
            String login = txtLogin.getText();
            funcionario.setLogin(login);
            String senha = String.valueOf(txtSenha.getPassword());
            funcionario.setSenha(senha);
            String email = txtEmail.getText();
            funcionario.setEmail(email);
            String cargo = txtCargo.getText();
            funcionario.setCargo(cargo);
            int nivel = Integer.parseInt(txtNivel.getText());
            funcionario.setNivel(nivel);
            conexao.conectar();
            conexao.cadastrarFuncionario(nome, cpf, login, senha, email, cargo, nivel);

            txtNome.setText("");
            tctCpf.setText("");
            txtLogin.setText("");
            txtSenha.setText("");
            txtEmail.setText("");
            txtCargo.setText("");
            txtNivel.setText("");
            txtNome.grabFocus();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo não pode ser vazio!");
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            String nome = txtNome.getText();
            funcionario.setNome(nome);
            String cpf = tctCpf.getText();
            funcionario.setCpf(cpf);
            String login = txtLogin.getText();
            funcionario.setLogin(login);
            String senha = String.valueOf(txtSenha.getPassword());
            funcionario.setSenha(senha);
            String email = txtEmail.getText();
            funcionario.setEmail(email);
            String cargo = txtCargo.getText();
            funcionario.setCargo(cargo);
            int nivel = Integer.parseInt(txtNivel.getText());
            funcionario.setNivel(nivel);
            conexao.conectar();
            conexao.alterarFuncionario(senha, login, nome, cpf, email, cargo, nivel);

            txtNome.setText("");
            tctCpf.setText("");
            txtLogin.setText("");
            txtSenha.setText("");
            txtEmail.setText("");
            txtCargo.setText("");
            txtNivel.setText("");
            tctCpf.grabFocus();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo não pode ser vazio!");
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNivel.grabFocus();
        }

    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNivelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNivelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Variable.habilitar == false) {
                txtLogin.grabFocus();
            } else {
                tctCpf.grabFocus();
            }
        }
    }//GEN-LAST:event_txtNivelKeyPressed

    private void tctCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tctCpfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Variable.habilitar == false) {
                btnConsultar.grabFocus();
            } else {
                txtLogin.grabFocus();
            }
        }
    }//GEN-LAST:event_tctCpfKeyPressed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenha.grabFocus();
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEmail.grabFocus();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCargo.grabFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Variable.habilitar == false) {
                btnAlterar.grabFocus();
            } else {
                btnCadastrar.grabFocus();
            }
        }
    }//GEN-LAST:event_txtCargoKeyPressed

    private void btnConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConsultarKeyPressed
        try {
            ArrayList<String> list = new ArrayList();

            Variable.cpf = tctCpf.getText();
            conexao.conectar();
            list = conexao.consultaFun();
            if (Variable.ckd) {
                lblId.setText(String.valueOf(list.get(0)));
                txtSenha.setText(list.get(1));
                txtLogin.setText(list.get(2));
                txtNome.setText(list.get(3));
                txtEmail.setText(list.get(4));
                txtCargo.setText(list.get(5));
                txtNivel.setText(list.get(6));
                Variable.cpf = "";
                txtNome.grabFocus();
            } else {
                tctCpf.setText("");
                tctCpf.grabFocus();
                Variable.cpf = "";
            }
            
            Variable.ckd = false;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campos não pode ser vazio");
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnConsultarKeyPressed

    private void btnAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAlterarKeyPressed
         try {
            String nome = txtNome.getText();
            funcionario.setNome(nome);
            String cpf = tctCpf.getText();
            funcionario.setCpf(cpf);
            String login = txtLogin.getText();
            funcionario.setLogin(login);
            String senha = String.valueOf(txtSenha.getPassword());
            funcionario.setSenha(senha);
            String email = txtEmail.getText();
            funcionario.setEmail(email);
            String cargo = txtCargo.getText();
            funcionario.setCargo(cargo);
            int nivel = Integer.parseInt(txtNivel.getText());
            funcionario.setNivel(nivel);
            conexao.conectar();
            conexao.alterarFuncionario(senha, login, nome, cpf, email, cargo, nivel);

            txtNome.setText("");
            tctCpf.setText("");
            txtLogin.setText("");
            txtSenha.setText("");
            txtEmail.setText("");
            txtCargo.setText("");
            txtNivel.setText("");
            tctCpf.grabFocus();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo não pode ser vazio!");
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnAlterarKeyPressed

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
       try {
            String nome = txtNome.getText();
            funcionario.setNome(nome);
            String cpf = tctCpf.getText();
            funcionario.setCpf(cpf);
            String login = txtLogin.getText();
            funcionario.setLogin(login);
            String senha = String.valueOf(txtSenha.getPassword());
            funcionario.setSenha(senha);
            String email = txtEmail.getText();
            funcionario.setEmail(email);
            String cargo = txtCargo.getText();
            funcionario.setCargo(cargo);
            int nivel = Integer.parseInt(txtNivel.getText());
            funcionario.setNivel(nivel);
            conexao.conectar();
            conexao.cadastrarFuncionario(nome, cpf, login, senha, email, cargo, nivel);

            txtNome.setText("");
            tctCpf.setText("");
            txtLogin.setText("");
            txtSenha.setText("");
            txtEmail.setText("");
            txtCargo.setText("");
            txtNivel.setText("");
            tctCpf.grabFocus();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo não pode ser vazio!");
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField tctCpf;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
